/* tslint:disable */
/* eslint-disable */
/**
 * SistemaMonitoreoAlimentacionApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Usuario
 */
export interface Usuario {
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'usuarioId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'nombre'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'apellidoPaterno'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'apellidoMaterno'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'usuariosCorreo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'password'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'imagenUsuario'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    'dosificadorId'?: string | null;
}

/**
 * UsuariosApi - axios parameter creator
 * @export
 */
export const UsuariosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/usuarios`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosIdDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUsuariosIdDelete', 'id', id)
            const localVarPath = `/api/usuarios/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {Usuario} [usuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosIdPut: async (id: string, usuario?: Usuario, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUsuariosIdPut', 'id', id)
            const localVarPath = `/api/usuarios/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usuario, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Usuario} [usuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosPost: async (usuario?: Usuario, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/usuarios`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usuario, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsuariosApi - functional programming interface
 * @export
 */
export const UsuariosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsuariosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsuariosGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Usuario>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUsuariosGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsuariosIdDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUsuariosIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {Usuario} [usuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsuariosIdPut(id: string, usuario?: Usuario, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUsuariosIdPut(id, usuario, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {Usuario} [usuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsuariosPost(usuario?: Usuario, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUsuariosPost(usuario, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UsuariosApi - factory interface
 * @export
 */
export const UsuariosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsuariosApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosGet(options?: any): AxiosPromise<Array<Usuario>> {
            return localVarFp.apiUsuariosGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosIdDelete(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiUsuariosIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {Usuario} [usuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosIdPut(id: string, usuario?: Usuario, options?: any): AxiosPromise<void> {
            return localVarFp.apiUsuariosIdPut(id, usuario, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Usuario} [usuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsuariosPost(usuario?: Usuario, options?: any): AxiosPromise<void> {
            return localVarFp.apiUsuariosPost(usuario, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsuariosApi - object-oriented interface
 * @export
 * @class UsuariosApi
 * @extends {BaseAPI}
 */
export class UsuariosApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsuariosApi
     */
    public apiUsuariosGet(options?: AxiosRequestConfig) {
        return UsuariosApiFp(this.configuration).apiUsuariosGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsuariosApi
     */
    public apiUsuariosIdDelete(id: string, options?: AxiosRequestConfig) {
        return UsuariosApiFp(this.configuration).apiUsuariosIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {Usuario} [usuario] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsuariosApi
     */
    public apiUsuariosIdPut(id: string, usuario?: Usuario, options?: AxiosRequestConfig) {
        return UsuariosApiFp(this.configuration).apiUsuariosIdPut(id, usuario, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Usuario} [usuario] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsuariosApi
     */
    public apiUsuariosPost(usuario?: Usuario, options?: AxiosRequestConfig) {
        return UsuariosApiFp(this.configuration).apiUsuariosPost(usuario, options).then((request) => request(this.axios, this.basePath));
    }
}


